language: clojure
lein: lein2
jdk:
 - oraclejdk7
before_install:
 - sudo add-apt-repository ppa:chris-lea/node.js -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq phantomjs nodejs
 - sudo npm install -g bower
install:
 - lein2 deps
 - lein2 cljx once
 - lein2 bower install
script:
 - lein2 test
 - lein2 cljsbuild test
