elasticsearch:
  image: dockerfile/elasticsearch
  expose:
    - "9200"
  volumes:
    - deploy/data/elasticsearch:/data/data
    - deploy/logs/elasticsearch:/data/log
mongodb:
  image: dockerfile/mongodb
  expose:
    - "27017"
  volumes:
    - deploy/data/mongodb:/data/db
parser:
  image: submanio/subman-parser
  links:
    - elasticsearch
    - mongodb
  environment:
    DB_HOST: "http://elasticsearch:9200"
    INDEX_NAME: "subman7"
    IS_DEBUG: "false"
    RAW_DB_HOST: "mongodb"
    RAW_DB_PORT: "27017"
    RAW_DB_NAME: "subman7"
web:
  image: submanio/subman-web
  links:
    - elasticsearch
  expose:
    - "3000"
  environment:
    DB_HOST: "http://elasticsearch:9200"
    INDEX_NAME: "subman7"
    IS_DEBUG: "false"
prerender:
  image: submanio/prerender
  links:
    - web
nginx:
  image: submanio/nginx
  domainname: subman.io
  links:
    - web
    - prerender
  volumes:
    - deploy/logs/nginx:/var/log/nginx
  volumes_from:
    - web
  ports:
    - "80:80"
maintain:
  image: submanio/subman-maintain
  links:
    - elasticsearch
    - mongodb
  environment:
    DB_HOST: "http://elasticsearch:9200"
    INDEX_NAME: "subman7"
    RAW_DB_HOST: "mongodb"
    RAW_DB_PORT: "27017"
    RAW_DB_NAME: "subman7"
